name: Deploy
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npx vercel --prod --token=${{ secrets.VERCEL_TOKEN }} --yes
        env:
          VERCEL_ORG_ID: team_vrfwmkE0YNU9nA2xK60tGMxu
          VERCEL_PROJECT_ID: prj_Axql1vbiuhaxaRQZs3Q473XctHoA
